NEUCONW:
  N_SAMPLES: 8 # 8
  N_IMPORTANCE: 16 # 16
  UP_SAMPLE_STEP: 2 # 2
  N_OUTSIDE: 4 #4
  USE_DISP: False
  PERTURB: 1.0
  NOISE_STD: 1.0

  NEAR_FAR_OVERRIDE: True
  DEPTH_LOSS: True
  S_VAL_BASE: 3
  BOUNDARY_SAMPLES: 10
  SAMPLE_RANGE: 16
  SDF_THRESHOLD: 0.0
  TRAIN_VOXEL_SIZE: 0.08
  UPDATE_FREQ: 5000 # 5000
  
  N_VOCAB: 5000
  ENCODE_A: True
  N_A: 48
  N_STATIC_HEAD: 1
  ANNEAL_END: 1500000  # 50000
 
  RENDER_BG: True
  MESH_MASK_LIST: ['sky']
  RAY_MASK_LIST:  ['person', 'car', 'bicycle', 'minibike']
  ENCODE_A_BG: True
  FLOOR_NORMAL: False
  FLOOR_LABELS: [ 'road' ]

# network config
  SDF_CONFIG:
    d_in: 3
    d_out: 513
    d_hidden: 512
    n_layers: 8
    skip_in: (4,)
    multires: 6
    bias: 0.5
    scale: 1
    geometric_init: True
    weight_norm: True
    inside_outside: False
    

  COLOR_CONFIG:
    d_in: 9
    d_feature: 512
    mode: "idr"
    d_out: 3
    d_hidden: 256 
    n_layers: 4
    head_channels: 128
    static_head_layers: 2
    weight_norm: True
    multires_view: 4

  S_CONFIG:
    init_val: 0.3

# loss config
  LOSS:
    coef: 1.0
    igr_weight: 0.01  #0.0001
    mask_weight: 0.1
    depth_weight: 0.1
    floor_weight: 0.01
    ##nelo
    curvature_weight: 0.00001  #0.0005

DATASET:
  ROOT_DIR: 'data/heritage-recon/brandenburg_gate'
  DATASET_NAME: 'phototourism'
  SPLIT: 'train'

  PHOTOTOURISM:
    IMG_DOWNSCALE: 1
    USE_CACHE: True  #True  False
    CACHE_DIR: 'cache_sgs'

TRAINER:
  CANONICAL_BS: 4096
  CANONICAL_LR: 5e-4

  OPTIMIZER: "adamw" 
  WEIGHT_DECAY: 0.01 

  LR_SCHEDULER: 'none'
  SAVE_DIR: './checkpoints'
  VAL_FREQ: 50000.0  # 10000.0
  SAVE_FREQ: 50000
  
###################hash grid
NELO:
  model:
    object:
        sdf:
            encoding:
                type: hashgrid
                levels: 16
                hashgrid:
                    min_logres: 5
                    max_logres: 11
                    dict_size: 21  # 22
                    dim: 8  # 8
                    range: [-4.0, 4.0]
                coarse2fine:
                    enabled: True
                    init_active_level: 8 # 
                    step: 50000 #5000
            gradient:
                mode: numerical   #numerical
                taps: 6
            warm_up_end: 25000 #5000